# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chief < Formula
  desc "Autonomous agent loop for working through PRDs with Claude Code"
  homepage "https://minicodemonkey.github.io/chief/"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MiniCodeMonkey/chief/releases/download/v0.1.0/chief_0.1.0_darwin_amd64.tar.gz"
      sha256 "d53c6066d60915daf44fc29ea4a0cf3bdf9c3bb66b70118b962e463530eda08d"

      def install
        bin.install "chief"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MiniCodeMonkey/chief/releases/download/v0.1.0/chief_0.1.0_darwin_arm64.tar.gz"
      sha256 "b3698e72d70014a59a71db02d5d999624e9316f55ce0e99b90a4491a467d30d8"

      def install
        bin.install "chief"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MiniCodeMonkey/chief/releases/download/v0.1.0/chief_0.1.0_linux_amd64.tar.gz"
      sha256 "3d6bf6c9cd74cb88c4426982ea9c9e71ca01e22c229c64ba1e5d1d33b8a6bec8"
      def install
        bin.install "chief"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MiniCodeMonkey/chief/releases/download/v0.1.0/chief_0.1.0_linux_arm64.tar.gz"
      sha256 "77b6efc4c7b51329d112638451720f03b02c6cae95e893e426b70934556fcf4a"
      def install
        bin.install "chief"
      end
    end
  end

  test do
    assert_match "chief", shell_output("#{bin}/chief --version")
  end
end
