# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chief < Formula
  desc "Autonomous agent loop for working through PRDs with Claude Code"
  homepage "https://minicodemonkey.github.io/chief/"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MiniCodeMonkey/chief/releases/download/v0.5.0/chief_0.5.0_darwin_amd64.tar.gz"
      sha256 "6c70591af6676b74f340ca76022d70a4afbb31c7ae2f711e2f739dc547b878a9"

      def install
        bin.install "chief"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MiniCodeMonkey/chief/releases/download/v0.5.0/chief_0.5.0_darwin_arm64.tar.gz"
      sha256 "ae037baea4eb76261e0f89cafe55ab2654ea605e6cc420876210ae39e8c64baa"

      def install
        bin.install "chief"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MiniCodeMonkey/chief/releases/download/v0.5.0/chief_0.5.0_linux_amd64.tar.gz"
      sha256 "172ebaf62c9b08fc1e063c8003aa9ba566e649a92de09adb14f81bf25ff29ac7"
      def install
        bin.install "chief"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MiniCodeMonkey/chief/releases/download/v0.5.0/chief_0.5.0_linux_arm64.tar.gz"
      sha256 "17c7a5f0640d0aebc127078893dac63a9fbe098f5d560898e8e50f9151798d1d"
      def install
        bin.install "chief"
      end
    end
  end

  test do
    assert_match "chief", shell_output("#{bin}/chief --version")
  end
end
